/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AdminAuditEntry {
    id: bigint;
    action: string;
    timestamp: bigint;
    details: string;
    targetPostId?: PostId;
    adminId: UserId;
    targetId?: UserId;
}
export type WithdrawalMethod = {
    __kind__: "upi";
    upi: string;
} | {
    __kind__: "bankTransfer";
    bankTransfer: {
        ifsc: string;
        accountNumber: string;
    };
};
export interface Comment {
    authorId: UserId;
    createdAt: bigint;
    text: string;
    postId: PostId;
}
export interface AdminPostInfo {
    id: PostId;
    likeCount: bigint;
    authorId: UserId;
    createdAt: bigint;
    caption: string;
    commentCount: bigint;
    mediaType: MediaType;
    isFlagged: boolean;
    flagCount: bigint;
}
export type TxId = bigint;
export type PostId = bigint;
export interface WalletTransaction {
    id: TxId;
    status: WalletTxStatus;
    userId: UserId;
    description: string;
    timestamp: bigint;
    withdrawalMethod?: WithdrawalMethod;
    txType: WalletTxType;
    amount: number;
}
export interface ReferralStats {
    referralCode: string;
    totalReferrals: bigint;
    totalEarned: number;
}
export interface FraudScoreInfo {
    flags: Array<string>;
    username: string;
    userId: UserId;
    riskScore: bigint;
}
export interface AdminAnalytics {
    pendingWithdrawals: bigint;
    totalUsers: bigint;
    totalWithdrawals: number;
    totalPosts: bigint;
    newUsersThisWeek: bigint;
    totalReels: bigint;
}
export type UserId = Principal;
export interface AdminReferralStats {
    totalReferrals: bigint;
    totalPaid: number;
    topReferrers: Array<{
        username: string;
        earnings: number;
    }>;
    pendingPayout: number;
}
export type MessageId = bigint;
export interface Post {
    id: PostId;
    authorId: UserId;
    createdAt: bigint;
    tags: Array<string>;
    mediaUrl: string;
    caption: string;
    mediaType: MediaType;
    location?: string;
}
export type NotificationId = bigint;
export interface WalletInfo {
    balance: number;
    transactions: Array<WalletTransaction>;
}
export interface Notification {
    id: NotificationId;
    createdAt: bigint;
    read: boolean;
    type: NotificationType;
    actorId: UserId;
    message?: string;
    recipientId: UserId;
    postId?: PostId;
}
export interface Message {
    id: MessageId;
    createdAt: bigint;
    text: string;
    receiverId: UserId;
    senderId: UserId;
}
export interface WithdrawalRequest {
    id: TxId;
    status: WithdrawalStatus;
    method: string;
    userId: UserId;
    createdAt: bigint;
    rejectionReason?: string;
    amount: number;
    accountDetails: string;
}
export interface UserProfile {
    bio: string;
    username: string;
    displayName: string;
    socialLinks: Array<string>;
    profilePhoto?: string;
    pronouns?: string;
}
export interface AdminUserInfo {
    postCount: bigint;
    username: string;
    displayName: string;
    userId: UserId;
    joinedAt: bigint;
    isActive: boolean;
    isSuspended: boolean;
    followerCount: bigint;
}
export enum MediaType {
    video = "video",
    photo = "photo"
}
export enum NotificationType {
    referralReel = "referralReel",
    like = "like",
    comment = "comment",
    referralFollowers = "referralFollowers",
    referralSignup = "referralSignup",
    follow = "follow"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum WalletTxStatus {
    pending = "pending",
    completed = "completed",
    approved = "approved",
    rejected = "rejected"
}
export enum WalletTxType {
    referralReel = "referralReel",
    withdrawal = "withdrawal",
    referralFollowers = "referralFollowers",
    referralSignup = "referralSignup"
}
export enum WithdrawalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    adminApproveWithdrawal(txId: TxId): Promise<void>;
    adminGetAllUsers(): Promise<Array<AdminUserInfo>>;
    adminGetAnalytics(): Promise<AdminAnalytics>;
    adminGetAuditLog(page: bigint, pageSize: bigint): Promise<Array<AdminAuditEntry>>;
    adminGetFlaggedPosts(): Promise<Array<AdminPostInfo>>;
    adminGetFraudScores(): Promise<Array<FraudScoreInfo>>;
    adminGetPosts(page: bigint, pageSize: bigint): Promise<Array<AdminPostInfo>>;
    adminGetReferralStats(): Promise<AdminReferralStats>;
    adminGetRewards(): Promise<{
        followerBonus: number;
        signupBonus: number;
        reelBonus: number;
    }>;
    adminGetUsers(page: bigint, pageSize: bigint): Promise<Array<AdminUserInfo>>;
    adminGetWithdrawalRequests(): Promise<Array<WithdrawalRequest>>;
    adminRejectWithdrawal(txId: TxId, reason: string): Promise<void>;
    adminRemovePost(postId: PostId): Promise<void>;
    adminSearchUsers(searchQuery: string): Promise<Array<AdminUserInfo>>;
    adminSetAdmin(userId: Principal): Promise<void>;
    adminSetRewards(signupBonus: number, reelBonus: number, followerBonus: number): Promise<boolean>;
    adminSuspendUser(userId: Principal): Promise<void>;
    adminUnsuspendUser(userId: Principal): Promise<void>;
    approveWithdrawal(txId: TxId): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createComment(postId: PostId, text: string): Promise<Comment>;
    createPost(mediaUrl: string, mediaType: MediaType, caption: string, location: string | null, tags: Array<string>): Promise<Post>;
    flagPost(postId: PostId): Promise<void>;
    followUser(followeeId: UserId): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getConversation(otherUserId: UserId): Promise<Array<Message>>;
    getExploreFeed(page: bigint, pageSize: bigint): Promise<Array<Post>>;
    getFollowers(userId: UserId): Promise<Array<UserId>>;
    getFollowing(userId: UserId): Promise<Array<UserId>>;
    getHomeFeed(page: bigint, pageSize: bigint): Promise<Array<Post>>;
    getMyWallet(): Promise<WalletInfo>;
    getNotifications(): Promise<Array<Notification>>;
    getPost(postId: PostId): Promise<Post | null>;
    getPostComments(postId: PostId): Promise<Array<Comment>>;
    getPostLikes(postId: PostId): Promise<Array<UserId>>;
    getRecentConversations(): Promise<Array<UserId>>;
    getReferralStats(): Promise<ReferralStats>;
    getUserPosts(userId: UserId): Promise<Array<Post>>;
    getUserProfile(userId: UserId): Promise<UserProfile | null>;
    getWithdrawalRequests(): Promise<Array<WalletTransaction>>;
    isAdmin(userId: Principal): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    markNotificationsAsRead(notificationIds: Array<NotificationId>): Promise<void>;
    registerUser(username: string, displayName: string, referralCode: string | null): Promise<UserProfile>;
    rejectWithdrawal(txId: TxId): Promise<void>;
    requestWithdrawal(amount: number, method: WithdrawalMethod): Promise<{
        __kind__: "ok";
        ok: WalletTransaction;
    } | {
        __kind__: "err";
        err: string;
    }>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchUsers(prefix: string): Promise<Array<UserProfile>>;
    sendMessage(receiverId: UserId, text: string): Promise<Message>;
    toggleLike(postId: PostId): Promise<boolean>;
    unfollowUser(followeeId: UserId): Promise<void>;
    updateProfile(displayName: string, bio: string, profilePhoto: string | null, pronouns: string | null, socialLinks: Array<string>): Promise<UserProfile>;
}
import type { AdminAuditEntry as _AdminAuditEntry, AdminPostInfo as _AdminPostInfo, MediaType as _MediaType, Notification as _Notification, NotificationId as _NotificationId, NotificationType as _NotificationType, Post as _Post, PostId as _PostId, TxId as _TxId, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole, WalletInfo as _WalletInfo, WalletTransaction as _WalletTransaction, WalletTxStatus as _WalletTxStatus, WalletTxType as _WalletTxType, WithdrawalMethod as _WithdrawalMethod, WithdrawalRequest as _WithdrawalRequest, WithdrawalStatus as _WithdrawalStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async adminApproveWithdrawal(arg0: TxId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminApproveWithdrawal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminApproveWithdrawal(arg0);
            return result;
        }
    }
    async adminGetAllUsers(): Promise<Array<AdminUserInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllUsers();
            return result;
        }
    }
    async adminGetAnalytics(): Promise<AdminAnalytics> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAnalytics();
            return result;
        }
    }
    async adminGetAuditLog(arg0: bigint, arg1: bigint): Promise<Array<AdminAuditEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAuditLog(arg0, arg1);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAuditLog(arg0, arg1);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetFlaggedPosts(): Promise<Array<AdminPostInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetFlaggedPosts();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetFlaggedPosts();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetFraudScores(): Promise<Array<FraudScoreInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetFraudScores();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetFraudScores();
            return result;
        }
    }
    async adminGetPosts(arg0: bigint, arg1: bigint): Promise<Array<AdminPostInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetPosts(arg0, arg1);
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetPosts(arg0, arg1);
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetReferralStats(): Promise<AdminReferralStats> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetReferralStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetReferralStats();
            return result;
        }
    }
    async adminGetRewards(): Promise<{
        followerBonus: number;
        signupBonus: number;
        reelBonus: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetRewards();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetRewards();
            return result;
        }
    }
    async adminGetUsers(arg0: bigint, arg1: bigint): Promise<Array<AdminUserInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetUsers(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetUsers(arg0, arg1);
            return result;
        }
    }
    async adminGetWithdrawalRequests(): Promise<Array<WithdrawalRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetWithdrawalRequests();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetWithdrawalRequests();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminRejectWithdrawal(arg0: TxId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminRejectWithdrawal(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminRejectWithdrawal(arg0, arg1);
            return result;
        }
    }
    async adminRemovePost(arg0: PostId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminRemovePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminRemovePost(arg0);
            return result;
        }
    }
    async adminSearchUsers(arg0: string): Promise<Array<AdminUserInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSearchUsers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSearchUsers(arg0);
            return result;
        }
    }
    async adminSetAdmin(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSetAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSetAdmin(arg0);
            return result;
        }
    }
    async adminSetRewards(arg0: number, arg1: number, arg2: number): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSetRewards(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSetRewards(arg0, arg1, arg2);
            return result;
        }
    }
    async adminSuspendUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSuspendUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSuspendUser(arg0);
            return result;
        }
    }
    async adminUnsuspendUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUnsuspendUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUnsuspendUser(arg0);
            return result;
        }
    }
    async approveWithdrawal(arg0: TxId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveWithdrawal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveWithdrawal(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n17(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n17(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createComment(arg0: PostId, arg1: string): Promise<Comment> {
        if (this.processError) {
            try {
                const result = await this.actor.createComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createComment(arg0, arg1);
            return result;
        }
    }
    async createPost(arg0: string, arg1: MediaType, arg2: string, arg3: string | null, arg4: Array<string>): Promise<Post> {
        if (this.processError) {
            try {
                const result = await this.actor.createPost(arg0, to_candid_MediaType_n19(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_opt_n21(this._uploadFile, this._downloadFile, arg3), arg4);
                return from_candid_Post_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPost(arg0, to_candid_MediaType_n19(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_opt_n21(this._uploadFile, this._downloadFile, arg3), arg4);
            return from_candid_Post_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async flagPost(arg0: PostId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.flagPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.flagPost(arg0);
            return result;
        }
    }
    async followUser(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.followUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.followUser(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConversation(arg0: UserId): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversation(arg0);
            return result;
        }
    }
    async getExploreFeed(arg0: bigint, arg1: bigint): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExploreFeed(arg0, arg1);
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExploreFeed(arg0, arg1);
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFollowers(arg0: UserId): Promise<Array<UserId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowers(arg0);
            return result;
        }
    }
    async getFollowing(arg0: UserId): Promise<Array<UserId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowing(arg0);
            return result;
        }
    }
    async getHomeFeed(arg0: bigint, arg1: bigint): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHomeFeed(arg0, arg1);
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHomeFeed(arg0, arg1);
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyWallet(): Promise<WalletInfo> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyWallet();
                return from_candid_WalletInfo_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyWallet();
            return from_candid_WalletInfo_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPost(arg0: PostId): Promise<Post | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPost(arg0);
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPost(arg0);
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPostComments(arg0: PostId): Promise<Array<Comment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPostComments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPostComments(arg0);
            return result;
        }
    }
    async getPostLikes(arg0: PostId): Promise<Array<UserId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPostLikes(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPostLikes(arg0);
            return result;
        }
    }
    async getRecentConversations(): Promise<Array<UserId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentConversations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentConversations();
            return result;
        }
    }
    async getReferralStats(): Promise<ReferralStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getReferralStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReferralStats();
            return result;
        }
    }
    async getUserPosts(arg0: UserId): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserPosts(arg0);
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserPosts(arg0);
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: UserId): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWithdrawalRequests(): Promise<Array<WalletTransaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWithdrawalRequests();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWithdrawalRequests();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async isAdmin(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markNotificationsAsRead(arg0: Array<NotificationId>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationsAsRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationsAsRead(arg0);
            return result;
        }
    }
    async registerUser(arg0: string, arg1: string, arg2: string | null): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1, to_candid_opt_n21(this._uploadFile, this._downloadFile, arg2));
                return from_candid_UserProfile_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1, to_candid_opt_n21(this._uploadFile, this._downloadFile, arg2));
            return from_candid_UserProfile_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectWithdrawal(arg0: TxId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectWithdrawal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectWithdrawal(arg0);
            return result;
        }
    }
    async requestWithdrawal(arg0: number, arg1: WithdrawalMethod): Promise<{
        __kind__: "ok";
        ok: WalletTransaction;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.requestWithdrawal(arg0, to_candid_WithdrawalMethod_n48(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestWithdrawal(arg0, to_candid_WithdrawalMethod_n48(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n51(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n51(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchUsers(arg0: string): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchUsers(arg0);
                return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchUsers(arg0);
            return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendMessage(arg0: UserId, arg1: string): Promise<Message> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1);
            return result;
        }
    }
    async toggleLike(arg0: PostId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleLike(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleLike(arg0);
            return result;
        }
    }
    async unfollowUser(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unfollowUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unfollowUser(arg0);
            return result;
        }
    }
    async updateProfile(arg0: string, arg1: string, arg2: string | null, arg3: string | null, arg4: Array<string>): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0, arg1, to_candid_opt_n21(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n21(this._uploadFile, this._downloadFile, arg3), arg4);
                return from_candid_UserProfile_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0, arg1, to_candid_opt_n21(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n21(this._uploadFile, this._downloadFile, arg3), arg4);
            return from_candid_UserProfile_n25(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AdminAuditEntry_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminAuditEntry): AdminAuditEntry {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_AdminPostInfo_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminPostInfo): AdminPostInfo {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_MediaType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MediaType): MediaType {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationType_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationType): NotificationType {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_Post_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Post): Post {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_WalletInfo_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WalletInfo): WalletInfo {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_WalletTransaction_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WalletTransaction): WalletTransaction {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_WalletTxStatus_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WalletTxStatus): WalletTxStatus {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_WalletTxType_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WalletTxType): WalletTxType {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawalMethod_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawalMethod): WithdrawalMethod {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawalRequest_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawalRequest): WithdrawalRequest {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawalStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawalStatus): WithdrawalStatus {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WithdrawalMethod]): WithdrawalMethod | null {
    return value.length === 0 ? null : from_candid_WithdrawalMethod_n38(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PostId]): PostId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Post]): Post | null {
    return value.length === 0 ? null : from_candid_Post_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserId]): UserId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TxId;
    status: _WithdrawalStatus;
    method: string;
    userId: _UserId;
    createdAt: bigint;
    rejectionReason: [] | [string];
    amount: number;
    accountDetails: string;
}): {
    id: TxId;
    status: WithdrawalStatus;
    method: string;
    userId: UserId;
    createdAt: bigint;
    rejectionReason?: string;
    amount: number;
    accountDetails: string;
} {
    return {
        id: value.id,
        status: from_candid_WithdrawalStatus_n14(_uploadFile, _downloadFile, value.status),
        method: value.method,
        userId: value.userId,
        createdAt: value.createdAt,
        rejectionReason: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.rejectionReason)),
        amount: value.amount,
        accountDetails: value.accountDetails
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PostId;
    authorId: _UserId;
    createdAt: bigint;
    tags: Array<string>;
    mediaUrl: string;
    caption: string;
    mediaType: _MediaType;
    location: [] | [string];
}): {
    id: PostId;
    authorId: UserId;
    createdAt: bigint;
    tags: Array<string>;
    mediaUrl: string;
    caption: string;
    mediaType: MediaType;
    location?: string;
} {
    return {
        id: value.id,
        authorId: value.authorId,
        createdAt: value.createdAt,
        tags: value.tags,
        mediaUrl: value.mediaUrl,
        caption: value.caption,
        mediaType: from_candid_MediaType_n9(_uploadFile, _downloadFile, value.mediaType),
        location: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.location))
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    username: string;
    displayName: string;
    socialLinks: Array<string>;
    profilePhoto: [] | [string];
    pronouns: [] | [string];
}): {
    bio: string;
    username: string;
    displayName: string;
    socialLinks: Array<string>;
    profilePhoto?: string;
    pronouns?: string;
} {
    return {
        bio: value.bio,
        username: value.username,
        displayName: value.displayName,
        socialLinks: value.socialLinks,
        profilePhoto: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.profilePhoto)),
        pronouns: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.pronouns))
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    action: string;
    timestamp: bigint;
    details: string;
    targetPostId: [] | [_PostId];
    adminId: _UserId;
    targetId: [] | [_UserId];
}): {
    id: bigint;
    action: string;
    timestamp: bigint;
    details: string;
    targetPostId?: PostId;
    adminId: UserId;
    targetId?: UserId;
} {
    return {
        id: value.id,
        action: value.action,
        timestamp: value.timestamp,
        details: value.details,
        targetPostId: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.targetPostId)),
        adminId: value.adminId,
        targetId: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.targetId))
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    balance: number;
    transactions: Array<_WalletTransaction>;
}): {
    balance: number;
    transactions: Array<WalletTransaction>;
} {
    return {
        balance: value.balance,
        transactions: from_candid_vec_n32(_uploadFile, _downloadFile, value.transactions)
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TxId;
    status: _WalletTxStatus;
    userId: _UserId;
    description: string;
    timestamp: bigint;
    withdrawalMethod: [] | [_WithdrawalMethod];
    txType: _WalletTxType;
    amount: number;
}): {
    id: TxId;
    status: WalletTxStatus;
    userId: UserId;
    description: string;
    timestamp: bigint;
    withdrawalMethod?: WithdrawalMethod;
    txType: WalletTxType;
    amount: number;
} {
    return {
        id: value.id,
        status: from_candid_WalletTxStatus_n35(_uploadFile, _downloadFile, value.status),
        userId: value.userId,
        description: value.description,
        timestamp: value.timestamp,
        withdrawalMethod: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.withdrawalMethod)),
        txType: from_candid_WalletTxType_n40(_uploadFile, _downloadFile, value.txType),
        amount: value.amount
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _NotificationId;
    createdAt: bigint;
    read: boolean;
    type: _NotificationType;
    actorId: _UserId;
    message: [] | [string];
    recipientId: _UserId;
    postId: [] | [_PostId];
}): {
    id: NotificationId;
    createdAt: bigint;
    read: boolean;
    type: NotificationType;
    actorId: UserId;
    message?: string;
    recipientId: UserId;
    postId?: PostId;
} {
    return {
        id: value.id,
        createdAt: value.createdAt,
        read: value.read,
        type: from_candid_NotificationType_n45(_uploadFile, _downloadFile, value.type),
        actorId: value.actorId,
        message: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.message)),
        recipientId: value.recipientId,
        postId: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.postId))
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PostId;
    likeCount: bigint;
    authorId: _UserId;
    createdAt: bigint;
    caption: string;
    commentCount: bigint;
    mediaType: _MediaType;
    isFlagged: boolean;
    flagCount: bigint;
}): {
    id: PostId;
    likeCount: bigint;
    authorId: UserId;
    createdAt: bigint;
    caption: string;
    commentCount: bigint;
    mediaType: MediaType;
    isFlagged: boolean;
    flagCount: bigint;
} {
    return {
        id: value.id,
        likeCount: value.likeCount,
        authorId: value.authorId,
        createdAt: value.createdAt,
        caption: value.caption,
        commentCount: value.commentCount,
        mediaType: from_candid_MediaType_n9(_uploadFile, _downloadFile, value.mediaType),
        isFlagged: value.isFlagged,
        flagCount: value.flagCount
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    video: null;
} | {
    photo: null;
}): MediaType {
    return "video" in value ? MediaType.video : "photo" in value ? MediaType.photo : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): WithdrawalStatus {
    return "pending" in value ? WithdrawalStatus.pending : "approved" in value ? WithdrawalStatus.approved : "rejected" in value ? WithdrawalStatus.rejected : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    approved: null;
} | {
    rejected: null;
}): WalletTxStatus {
    return "pending" in value ? WalletTxStatus.pending : "completed" in value ? WalletTxStatus.completed : "approved" in value ? WalletTxStatus.approved : "rejected" in value ? WalletTxStatus.rejected : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upi: string;
} | {
    bankTransfer: {
        ifsc: string;
        accountNumber: string;
    };
}): {
    __kind__: "upi";
    upi: string;
} | {
    __kind__: "bankTransfer";
    bankTransfer: {
        ifsc: string;
        accountNumber: string;
    };
} {
    return "upi" in value ? {
        __kind__: "upi",
        upi: value.upi
    } : "bankTransfer" in value ? {
        __kind__: "bankTransfer",
        bankTransfer: value.bankTransfer
    } : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    referralReel: null;
} | {
    withdrawal: null;
} | {
    referralFollowers: null;
} | {
    referralSignup: null;
}): WalletTxType {
    return "referralReel" in value ? WalletTxType.referralReel : "withdrawal" in value ? WalletTxType.withdrawal : "referralFollowers" in value ? WalletTxType.referralFollowers : "referralSignup" in value ? WalletTxType.referralSignup : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    referralReel: null;
} | {
    like: null;
} | {
    comment: null;
} | {
    referralFollowers: null;
} | {
    referralSignup: null;
} | {
    follow: null;
}): NotificationType {
    return "referralReel" in value ? NotificationType.referralReel : "like" in value ? NotificationType.like : "comment" in value ? NotificationType.comment : "referralFollowers" in value ? NotificationType.referralFollowers : "referralSignup" in value ? NotificationType.referralSignup : "follow" in value ? NotificationType.follow : value;
}
function from_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _WalletTransaction;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: WalletTransaction;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_WalletTransaction_n33(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AdminAuditEntry>): Array<AdminAuditEntry> {
    return value.map((x)=>from_candid_AdminAuditEntry_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WithdrawalRequest>): Array<WithdrawalRequest> {
    return value.map((x)=>from_candid_WithdrawalRequest_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Post>): Array<Post> {
    return value.map((x)=>from_candid_Post_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WalletTransaction>): Array<WalletTransaction> {
    return value.map((x)=>from_candid_WalletTransaction_n33(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n43(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AdminPostInfo>): Array<AdminPostInfo> {
    return value.map((x)=>from_candid_AdminPostInfo_n7(_uploadFile, _downloadFile, x));
}
function to_candid_MediaType_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MediaType): _MediaType {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n52(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_WithdrawalMethod_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WithdrawalMethod): _WithdrawalMethod {
    return to_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    username: string;
    displayName: string;
    socialLinks: Array<string>;
    profilePhoto?: string;
    pronouns?: string;
}): {
    bio: string;
    username: string;
    displayName: string;
    socialLinks: Array<string>;
    profilePhoto: [] | [string];
    pronouns: [] | [string];
} {
    return {
        bio: value.bio,
        username: value.username,
        displayName: value.displayName,
        socialLinks: value.socialLinks,
        profilePhoto: value.profilePhoto ? candid_some(value.profilePhoto) : candid_none(),
        pronouns: value.pronouns ? candid_some(value.pronouns) : candid_none()
    };
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MediaType): {
    video: null;
} | {
    photo: null;
} {
    return value == MediaType.video ? {
        video: null
    } : value == MediaType.photo ? {
        photo: null
    } : value;
}
function to_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "upi";
    upi: string;
} | {
    __kind__: "bankTransfer";
    bankTransfer: {
        ifsc: string;
        accountNumber: string;
    };
}): {
    upi: string;
} | {
    bankTransfer: {
        ifsc: string;
        accountNumber: string;
    };
} {
    return value.__kind__ === "upi" ? {
        upi: value.upi
    } : value.__kind__ === "bankTransfer" ? {
        bankTransfer: value.bankTransfer
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
